"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var STATUSCODE_ENUM;
(function (STATUSCODE_ENUM) {
    STATUSCODE_ENUM[STATUSCODE_ENUM["UNKNOWN_ERROR"] = 0] = "UNKNOWN_ERROR";
    STATUSCODE_ENUM[STATUSCODE_ENUM["FORM_REQUIREMENT_ERROR"] = 1] = "FORM_REQUIREMENT_ERROR";
    STATUSCODE_ENUM[STATUSCODE_ENUM["PAGE_NOT_FOUND"] = 2] = "PAGE_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["RESOURCE_NOT_FOUND"] = 3] = "RESOURCE_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["RESOURCE_ALREADY_EXIST"] = 4] = "RESOURCE_ALREADY_EXIST";
    STATUSCODE_ENUM[STATUSCODE_ENUM["SUCCESS"] = 5] = "SUCCESS";
    STATUSCODE_ENUM[STATUSCODE_ENUM["ORIGIN_NOT_ALLOWED"] = 6] = "ORIGIN_NOT_ALLOWED";
    STATUSCODE_ENUM[STATUSCODE_ENUM["UNAUTHORIZED"] = 7] = "UNAUTHORIZED";
    STATUSCODE_ENUM[STATUSCODE_ENUM["FORBIDDEN"] = 8] = "FORBIDDEN";
    STATUSCODE_ENUM[STATUSCODE_ENUM["EVENT_SENT_SUCCESSFULLY"] = 9] = "EVENT_SENT_SUCCESSFULLY";
    STATUSCODE_ENUM[STATUSCODE_ENUM["EVENT_NOT_SENT"] = 10] = "EVENT_NOT_SENT";
})(STATUSCODE_ENUM || (STATUSCODE_ENUM = {}));
