"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EMAIL_TEMPLATES = void 0;
const modules_1 = require("../modules");
var STATUSCODE_ENUM;
(function (STATUSCODE_ENUM) {
    STATUSCODE_ENUM[STATUSCODE_ENUM["UNKNOWN_ERROR"] = 0] = "UNKNOWN_ERROR";
    STATUSCODE_ENUM[STATUSCODE_ENUM["FORM_REQUIREMENT_ERROR"] = 1] = "FORM_REQUIREMENT_ERROR";
    STATUSCODE_ENUM[STATUSCODE_ENUM["PAGE_NOT_FOUND"] = 2] = "PAGE_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["RESOURCE_NOT_FOUND"] = 3] = "RESOURCE_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["RESOURCE_ALREADY_EXIST"] = 4] = "RESOURCE_ALREADY_EXIST";
    STATUSCODE_ENUM[STATUSCODE_ENUM["SUCCESS"] = 5] = "SUCCESS";
    STATUSCODE_ENUM[STATUSCODE_ENUM["ORIGIN_NOT_ALLOWED"] = 6] = "ORIGIN_NOT_ALLOWED";
    STATUSCODE_ENUM[STATUSCODE_ENUM["UNAUTHORIZED"] = 7] = "UNAUTHORIZED";
    STATUSCODE_ENUM[STATUSCODE_ENUM["FORBIDDEN"] = 8] = "FORBIDDEN";
    STATUSCODE_ENUM[STATUSCODE_ENUM["EVENT_SENT_SUCCESSFULLY"] = 9] = "EVENT_SENT_SUCCESSFULLY";
    STATUSCODE_ENUM[STATUSCODE_ENUM["EVENT_NOT_SENT"] = 10] = "EVENT_NOT_SENT";
    STATUSCODE_ENUM[STATUSCODE_ENUM["USER_NOT_FOUND"] = 11] = "USER_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOGIN_SUCCESSFUL"] = 12] = "LOGIN_SUCCESSFUL";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOGOUT_SUCCESSFUL"] = 13] = "LOGOUT_SUCCESSFUL";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOGIN_FAILED"] = 14] = "LOGIN_FAILED";
    STATUSCODE_ENUM[STATUSCODE_ENUM["PASSWORD_RESET_TOKEN_SENT"] = 15] = "PASSWORD_RESET_TOKEN_SENT";
    STATUSCODE_ENUM[STATUSCODE_ENUM["INCORRECT_PASSWORD"] = 16] = "INCORRECT_PASSWORD";
    STATUSCODE_ENUM[STATUSCODE_ENUM["BAD_REQUEST"] = 17] = "BAD_REQUEST";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOGIN_RECORDS_FOUND"] = 18] = "LOGIN_RECORDS_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOGIN_RECORDS_NOT_FOUND"] = 19] = "LOGIN_RECORDS_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["ACCOUNT_ACTIVATED_ALREADY"] = 20] = "ACCOUNT_ACTIVATED_ALREADY";
    STATUSCODE_ENUM[STATUSCODE_ENUM["PASSWORD_RESET_SUCCESSFUL"] = 21] = "PASSWORD_RESET_SUCCESSFUL";
})(STATUSCODE_ENUM || (STATUSCODE_ENUM = {}));
exports.EMAIL_TEMPLATES = {
    ACCOUNT_ACTIVATION: (0, modules_1.getGlobalEnv)("ACCOUNT_ACTIVATION_EMAIL_TEMPLATE"),
    PASSWORD_RESET_TOKEN: (0, modules_1.getGlobalEnv)("PASSWORD_RESET_TOKEN_EMAIL_TEMPLATE"),
    PASSWORD_RESET_SUCCESSFUL: (0, modules_1.getGlobalEnv)("PASSWORD_RESET_SUCCESSFUL"),
    CHANGE_PASSWORD: (0, modules_1.getGlobalEnv)("CHANGE_PASSWORD"),
    ACCOUNT_ACTIVATION_SUCCESS: (0, modules_1.getGlobalEnv)("ACCOUNT_ACTIVATION_SUCCESS"),
};
